# Generated by Django 2.2.4 on 2019-09-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('numero_camas', models.IntegerField()),
                ('cama', models.CharField(max_length=10)),
            ],
            options={
                'permissions': {('is_administrador', 'Usuario Administrador')},
            },
        ),
    ]
