# Generated by Django 2.2.4 on 2019-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaVisita',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(max_length=40)),
                ('hora_comienzo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion_recidencia', models.CharField(max_length=40)),
                ('telefono_recidencia', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.Diagnostico')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.Medico')),
                ('historia_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.HistoriaClinica')),
                ('tarjeta_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.TarjetaVisita')),
            ],
        ),
    ]
