# Generated by Django 2.2.4 on 2019-09-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20190830_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': {('is_paciente', 'Usuario Paciente')}},
        ),
    ]
