# Generated by Django 2.2.4 on 2019-09-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20190831_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono_recidencia',
            field=models.CharField(max_length=12),
        ),
    ]
